import {
  Activity,
  ArrowLeftRight,
  Baby,
  BadgeCheck,
  BedDouble,
  Bone,
  Brain,
  Building2,
  CalendarCheck,
  CalendarClock,
  CarFront,
  CarTaxiFront,
  ClipboardCheck,
  Compass,
  Eye,
  FileText,
  Globe,
  HandHeart,
  Handshake,
  Headset,
  HeartPulse,
  Hospital,
  Hotel,
  House,
  IdCard,
  Landmark,
  Languages,
  Luggage,
  Mail,
  MessageCircle,
  Network,
  PlaneLanding,
  PlaneTakeoff,
  ReceiptText,
  Ribbon,
  Route,
  Scale,
  ShieldCheck,
  Smile,
  Stethoscope,
  UserCheck,
  UsersRound,
  Weight,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

/**
 * Data files reference icons by name so content stays serialisable.
 * The design used Material Symbols Rounded (weight 300); Lucide at a
 * 1.75 stroke is the closest match within the approved stack.
 */
const icons = {
  activity: Activity,
  baby: Baby,
  "badge-check": BadgeCheck,
  bed: BedDouble,
  bone: Bone,
  brain: Brain,
  building: Building2,
  "calendar-check": CalendarCheck,
  "calendar-clock": CalendarClock,
  car: CarFront,
  "clipboard-check": ClipboardCheck,
  compare: ArrowLeftRight,
  compass: Compass,
  eye: Eye,
  file: FileText,
  globe: Globe,
  "hand-heart": HandHeart,
  handshake: Handshake,
  headset: Headset,
  "heart-pulse": HeartPulse,
  hospital: Hospital,
  hotel: Hotel,
  house: House,
  "id-card": IdCard,
  landmark: Landmark,
  languages: Languages,
  luggage: Luggage,
  mail: Mail,
  message: MessageCircle,
  network: Network,
  "plane-landing": PlaneLanding,
  "plane-takeoff": PlaneTakeoff,
  receipt: ReceiptText,
  ribbon: Ribbon,
  route: Route,
  scale: Scale,
  "shield-check": ShieldCheck,
  smile: Smile,
  stethoscope: Stethoscope,
  taxi: CarTaxiFront,
  "user-check": UserCheck,
  users: UsersRound,
  weight: Weight,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function Icon({ name, strokeWidth = 1.75, ...props }: { name: IconName } & LucideProps) {
  const Component = icons[name];
  return <Component aria-hidden="true" strokeWidth={strokeWidth} {...props} />;
}
